config/routes.rb
GlutenFree::Application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  resources :products

  root :to => 'products#index'

  match 'search', :to => 'products#search', :as => :search

  get 'about', :to => 'welcome#about', :as => :about

end

app/models/admin_user.rb
#class AdminUser < ActiveRecord::Base
#  # Include default devise modules. Others available are:
#  # :token_authenticatable, :confirmable,
#  # :lockable, :timeoutable and :omniauthable
#  devise :database_authenticatable, 
#         :recoverable, :rememberable, :trackable, :validatable
#
#  # Setup accessible (or protected) attributes for your model
#  attr_accessible :email, :password, :password_confirmation, :remember_me
#  # attr_accessible :title, :body
#end

app/models/product.rb
class Product # < ActiveRecord::Base

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :review, :type => String

  field :has_dairy, :type => Boolean, :default => true
  field :has_eggs, :type => Boolean, :default => true
  field :has_soy, :type => Boolean, :default => true

  field :is_gf, :type => Boolean, :default => false
  field :is_dedicated, :type => Boolean, :default => false
  field :is_gmp, :type => Boolean, :default => false

  field :rating, :type => Integer, :default => 3
  field :n_servings, :type => Integer, :default => 1

  field :packaging, :type => Symbol, :default => :paper

  field :temperature, :type => Symbol, :default => :room

  PACKAGING = [ :cardboard, :glass, :paper, :plastic ]

  TEMPERATURE = [ :room, :frozen, :refrigerated ]

  #
  # `more...`
  #
  field :descr, :type => String
  field :upc, :type => String
  field :preparation_notes, :type => String
  field :found_at, :type => String
  field :sold_at,  :type => String
  field :ingredients_list, :type => String


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_defaults

  private

  def set_defaults
    @action_name = params[:controller].gsub('/', '_') + '_' + params[:action]
    @action_classes = "#{params[:controller].gsub('/', '_')} #{params[:action]}" # #{@locale}
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def search
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def image_product product = {}
    link_to image_tag( 'missing.png', :class => :thumb, :alt => '' ), '#', :class => :thumbnail
  end

  def image_search
    image_tag 'search.png', :alt => ''
  end

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Gluten Free
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
  %body{ :id => @action_name }
    .container
      -# %h1 Gluten Free

      .navbar.header-main
        .navbar-inner
          = link_to 'Gluten Free', root_path, :class => :brand
          %ul.nav
            %li.products-index= link_to 'Products', products_path
            %li.products-new
              = link_to 'Add New', new_product_path
            %li.products-search-link= link_to 'Search', '#'

            -# %li.welcome-about= link_to 'About', '#'
            
      = render 'products/search'
      
      = yield

      %footer{ :class => :footer }
        .row-fluid
          .span4
            ^__^
          .span4
            Copyright &copy; 2013 CAC
          .span4
            = link_to 'About this site', about_path

app/views/products/_search.haml
- product = Product.new

.products-search
  = form_for product, :url => search_path do |f|
    .product
      .inner
        .row-fluid
          .span12
            = f.text_field :name
        .row-fluid
          .span2.thumbnail
            = image_tag('search.png', :class => :thumb )
          .span9
            .row-fluid
              .span6
                .btn-group
                  .btn{ 'data-toggle' => 'dropdown' }
                    Packaging
                    %span{ :class => :caret }                      
                  %ul.dropdown-menu
                    %li= link_to 'Paper', '#'
                    %li= link_to 'Plastic', '#'
                    
              .span6
                .btn-group
                  .btn{ 'data-toggle' => 'dropdown' }
                    Temperature
                    %span{ :class => :caret }
                  %ul.dropdown-menu
                    %li= link_to 'Room temperature'
                    %li= link_to 'Frozen'
                    %li= link_to 'Refrigerated'
                    
            .row-fluid.toggles
              .span6
                .row-fluid
                  .btn Y
                  Gluten Free?
                .row-fluid
                  .btn Y
                  GMP certified?
                .row-fluid
                  .btn Y
                  Dedicated facility?
              .span6
                .row-fluid
                  .btn.action Y
                  .btn.action N
                  .btn.action Either
                  Has dairy?
                  
                .row-fluid
                  .btn.action Y
                  .btn.action N
                  .btn.action Either
                  Has soy?
                  
                .row-fluid
                  .btn.action Y
                  .btn.action N
                  .btn.action Either
                  Has eggs?
                  
            .row-fluid
              .span6.label
                .n_servings
                  = f.text_field :n_servings
                  \# of servings
              .span6
                .rating                
                  - (1..5).each do |i|
                    = image_tag 'star_gray.png'
                
          .span1
            .more-field
              = image_tag 'more.png'
              More Search Options

app/views/products/index.haml
-# search thing

.products
  - @products.each do |product|
    .product
      .inner
        .row-fluid
          .span12
            %h4= product.name.titleize
        .row-fluid
          .span2
            = image_tag 'product.jpg'
          .span9
            .row-fluid
              .span6.label{ :class => product.packaging }
                .packaging
                  = product.packaging
              .span6.label{ :class => product.temperature }
                .temperature
                  = product.temperature
                  
            .row-fluid.toggles
              .span6
                .row-fluid
                  - if product.is_gf
                    .btn.btn-success Y
                  - else
                    .btn.btn-warning N
                  Gluten Free?
                .row-fluid
                  - if product.is_gmp
                    .btn.btn-success Y
                  - else
                    .btn.btn-warning N
                  GMP certified?
                .row-fluid
                  - if product.is_dedicated
                    .btn.btn-success Y
                  - else
                    .btn.btn-warning N
                  Dedicated facility?
              .span6
                .row-fluid
                  - if product.has_dairy
                    .btn.btn-success Y
                    .btn.action N
                  - else
                    .btn.action Y
                    .btn.btn-warning N
                  Has dairy?
                .row-fluid
                  - if product.has_soy
                    .btn.btn-success Y
                    .btn.action N
                  - else
                    .btn.action Y
                    .btn.btn-warning N
                  Has soy?
                .row-fluid
                  - if product.has_eggs
                    .btn.btn-success Y
                    .btn.action N
                  - else
                    .btn.action Y
                    .btn.btn-warning N
                  Has eggs?
                
            .row-fluid
              .span6.label
                .n_servings= "#{ product.n_servings } servings"
              .span6
                .rating                
                  - (1..product.rating).each do |i|
                    = image_tag 'star.png'
                
          .span1
            .more-field
              = image_tag 'more.png'
              More Info